import { NextRequest, NextResponse } from 'next/server'

const viloes = [
  { posicao: 1, nome: 'Adolf Hitler', terra_natal: 'Braunau Am Inn, Áustria', nascimento: '20/04/1889', morte: '30/04/1945', texto: 'Com ascensão meteórica no partido nazista alemão, virou chanceler em 1933 e lançou o mundo no caos da 2ª Guerra Mundial. Pregando a superioridade racial, sistematizou a eliminação de cerca de 8 milhões de judeus e membros de outras minorias em campos de extermínio. É considerado o maior criminoso da história moderna.' },
  { posicao: 2, nome: 'Josef Stalin', terra_natal: 'Gori, Rússia', nascimento: '18/12/1878', morte: '05/03/1953', texto: 'Ditador da União Soviética de 1922 a 1953, sua paranoia custou a vida de cerca de 20 a 60 milhões de pessoas. Criou os gulags — campos de trabalho forçado — onde milhões morreram. Promoveu a coletivização forçada que causou a fome da Ucrânia (Holodomor), matando milhões.' },
  { posicao: 3, nome: 'Mao Tsé-Tung', terra_natal: 'Shaoshan, China', nascimento: '26/12/1893', morte: '09/09/1976', texto: 'De 1943 a 1976, Mao eliminou quem criticava sua liderança e forçou o povo a trabalhar em regime de escravidão. Segundo a ONU, causou a morte de 45 milhões de pessoas — incluindo cerca de 700 mil que se suicidaram diante da situação do país. O Grande Salto Adiante (1958-1962) causou a maior fome da história humana.' },
  { posicao: 4, nome: 'Gêngis Khan', terra_natal: 'Mongólia', nascimento: '1162', morte: '1227', texto: 'Fundador do maior império terrestre da história, Khan conquistou desde a China até o mar Cáspio, deixando um rastro de 40 a 60 milhões de mortes — cerca de 10% da população mundial da época. Cidades inteiras foram destruídas. Bagdá, capital cultural do mundo islâmico, foi saqueada e incendiada em 1258.' },
  { posicao: 5, nome: 'Napoleão Bonaparte', terra_natal: 'Ajaccio, Córsega, França', nascimento: '15/08/1769', morte: '05/05/1821', texto: 'Líder político e militar que ascendeu ao poder no final da Revolução Francesa e tornou-se imperador. Suas guerras de conquista causaram a morte de 3 a 6 milhões de europeus. Ignorou tratados internacionais e foi vencido por sua própria ambição, ao esgotar o poderio militar francês em campanhas suicidas.' },
  { posicao: 6, nome: 'Pol Pot', terra_natal: 'Camboja', nascimento: '19/05/1925', morte: '15/04/1998', texto: 'Líder dos Khmer Vermelhos, transformou o Camboja numa câmara de horrores entre 1975 e 1979. Perseguiu todo tipo de intelectual — quem usasse óculos era suspeito. Matou cerca de 1,5 a 2 milhões de pessoas, um quarto da população do Camboja, em campos de trabalho forçado. Ficou famoso por colecionar crânios de suas vítimas nos "Killing Fields".' },
  { posicao: 7, nome: 'Idi Amin', terra_natal: 'Koboko, Uganda', nascimento: 'c. 1925', morte: '16/08/2003', texto: 'Declarou-se presidente vitalício da Uganda após um golpe de Estado em 1971. Seu grupo de "conselheiros" despachou mais de 300 mil opositores. A loucura do tirano era tão extrema que sua esposa foi encontrada mutilada. Se autoproclamou "Conquistador do Império Britânico" e "Rei da Escócia". Morreu exilado na Arábia Saudita sem jamais ser julgado.' },
  { posicao: 8, nome: 'Saddam Hussein', terra_natal: 'Tikrit, Iraque', nascimento: '28/04/1937', morte: '30/12/2006', texto: 'Ditador militar iraquiano entre 1979 e 2003. Perseguiu e eliminou opositores políticos, promoveu a limpeza étnica da população curda no norte do país e usou armas químicas contra civis. Em 1990, deflagrou a Guerra do Golfo ao invadir o Kuwait. Foi capturado, julgado e enforcado em 2006.' },
  { posicao: 9, nome: 'Nero', terra_natal: 'Anzio, Itália', nascimento: '15/12/37', morte: '09/06/68', texto: 'O quinto imperador romano adorava torturar e matar cristãos. Também matou sua própria mãe por paranoia, incendiou Roma em 64 d.C. (o incêndio durou seis dias) e mandou matar o apóstolo Paulo. Sua crueldade se tornou lendária e seu nome sinônimo de tirania e loucura imperial.' },
  { posicao: 10, nome: 'Francisco Franco', terra_natal: 'Ferrol, Espanha', nascimento: '04/12/1892', morte: '20/11/1975', texto: 'O Generalíssimo controlou a Espanha com mão de ferro de 1939 até sua morte. Chegou ao poder com uma guerra civil que custou a vida de 500 mil espanhóis e ainda matou mais 200 mil de fome, após desviar dinheiro para os esforços militares. Aliou seus ideais políticos com os de Hitler e Mussolini.' },
  { posicao: 11, nome: 'Leopoldo II', terra_natal: 'Bruxelas, Bélgica', nascimento: '09/04/1835', morte: '17/12/1909', texto: 'O rei belga explorou brutalmente o marfim e a borracha no Estado Livre do Congo a partir de 1884. Para obter eficiência máxima, determinou um rígido sistema de trabalhos forçados que matou 3 a 10 milhões de congoleses — muitos porque não conseguiam cumprir sua cota de produtividade. Amputação de mãos era punição comum.' },
  { posicao: 12, nome: 'Osama bin Laden', terra_natal: 'Riad, Arábia Saudita', nascimento: '10/03/1957', morte: '02/05/2011', texto: 'Líder da rede terrorista Al-Qaeda, orquestrou os ataques de 11 de setembro que assassinaram mais de 3 mil pessoas. Sua organização também causou atentados às embaixadas dos EUA na Tanzânia e no Quênia. Foi morto numa operação especial americana no Paquistão em 2011.' },
  { posicao: 13, nome: 'Henrique VIII da Inglaterra', terra_natal: 'Greenwich, Inglaterra', nascimento: '28/06/1491', morte: '28/01/1547', texto: 'Rei da Inglaterra, Henrique VIII é famoso por suas seis esposas, das quais duas foram executadas. Para anular seu primeiro casamento, rompeu com o papado em 1534 e criou a Igreja Anglicana. Mandou executar Thomas More, seu chanceler e amigo, e dezenas de outros que se opuseram a ele. Dissolveu os monastérios e confiscou suas riquezas.' },
  { posicao: 14, nome: 'Hernán Cortés', terra_natal: 'Medellín, Espanha', nascimento: '1485', morte: '02/12/1547', texto: 'Conquistador espanhol que destruiu o Império Asteca com apenas 500 homens entre 1519 e 1521. Aproveitou alianças com povos subjugados pelos astecas e a devastação da varíola — que matou metade da população indígena — para derrubar um Império de 25 milhões de pessoas. Tenochtitlan foi destruída e reconstruída como Cidade do México colonial.' },
  { posicao: 15, nome: 'Rasputin', terra_natal: 'Pokrovskoye, Rússia', nascimento: '22/01/1869', morte: '30/12/1916', texto: 'O monge errante siberiano ganhou influência extraordinária sobre a família imperial russa ao aparentemente aliviar a hemofilia do czarevich Alexei. A czarina Alexandra tornou-se totalmente dependente de Rasputin, que influenciava decisões políticas. Foi assassinado em 1916 por nobres: envenenado, baleado e afogado. Seu assassinato acelerou a queda dos Romanov.' },
  { posicao: 16, nome: 'Rafael Trujillo', terra_natal: 'San Cristóbal, Rep. Dominicana', nascimento: '24/10/1891', morte: '30/05/1961', texto: 'Ditador da República Dominicana por 31 anos. Em 1937, ordenou o Massacre do Salsa — assassinato de 20 a 30 mil haitianos usando como critério a pronúncia da palavra "perejil". Acumulou 65% da terra arável do país. Foi assassinado em emboscada em 1961, provavelmente com cumplicidade da CIA.' },
  { posicao: 17, nome: 'Mobutu Sese Seko', terra_natal: 'Congo', nascimento: '14/10/1930', morte: '07/09/1997', texto: 'Governou o Congo/Zaire por 32 anos (1965-1997), tornando-se sinônimo de cleptocracias africanas. Acumulou US$ 5 bilhões em contas bancárias estrangeiras enquanto o povo morria de fome num dos países mais ricos em recursos naturais do mundo. Rebatizou-se com um nome que significa "guerreiro que avança de vitória em vitória".' },
  { posicao: 18, nome: 'Francisco Solano López', terra_natal: 'Assunção, Paraguai', nascimento: '24/07/1827', morte: '01/03/1870', texto: 'Ditador paraguaio que arrastou seu país à Guerra da Tríplice Aliança (1864-1870) contra Brasil, Argentina e Uruguai. Estima-se que 60 a 70% da população paraguaia morreu, incluindo a maioria dos homens adultos. López executou seu próprio irmão e cunhadas acusados de conspiração. Morreu em combate recusando-se a se render.' },
  { posicao: 19, nome: 'Mengistu Haile Mariam', terra_natal: 'Etiópia', nascimento: '1937', morte: 'Ainda vivo', texto: 'Governou a Etiópia de 1974 a 1991 como chefe da junta militar marxista Derg. O "Terror Vermelho" matou entre 30 mil e 500 mil opositores. A grande fome de 1983-85 — exacerbada pela coletivização forçada — matou até 1 milhão de etíopes. Fugiu para o Zimbábue em 1991, onde Robert Mugabe o protegeu. Condenado à morte por genocídio em 2006, nunca foi extraditado.' },
  { posicao: 20, nome: 'Bashar al-Assad', terra_natal: 'Damasco, Síria', nascimento: '11/09/1965', morte: 'Ainda vivo', texto: 'Presidente da Síria desde 2000. Quando protestos pacíficos eclodiram em 2011, respondeu com tanques e prisões. A repressão transformou-se em guerra civil: mais de 500 mil mortos e 13 milhões de deslocados — metade da população síria. Usou armas químicas (gás sarín) contra civis em crimes de guerra documentados pela ONU.' },
]

const inventores = [
  { nome: 'Leonardo da Vinci', pais: 'Itália', nascimento: '15/04/1452', morte: '02/05/1519', invencao: 'Máquina voadora, tank, helicóptero (conceitos)', texto: 'Leonardo da Vinci foi o epítome do Homem Renascentista — pintor, escultor, arquiteto, engenheiro, anatomista e filósofo. Seus cadernos de notas contêm esboços de máquinas voadoras, veículos blindados, pontes giratórias e robôs 300 anos antes de qualquer pessoa construí-los. Suas pinturas — Mona Lisa e Último Ceia — são as obras de arte mais famosas do mundo. Sua anatomia humana, baseada em dissecação de cadáveres, foi revolucionária.' },
  { nome: 'Nikola Tesla', pais: 'Sérvia/EUA', nascimento: '10/07/1856', morte: '07/01/1943', invencao: 'Corrente Alternada, motor elétrico AC, rádio (disputado)', texto: 'Tesla revolucionou a engenharia elétrica com o desenvolvimento do sistema de corrente alternada (CA), que derrotou a corrente contínua de Edison para se tornar o padrão global. Sem o trabalho de Tesla, o mundo moderno não existiria como conhecemos. Suas pesquisas sobre transmissão de energia sem fio e ondas de rádio estavam décadas à frente. Morreu sozinho e empobrecido, enquanto Edison e Westinghouse ficaram milionários.' },
  { nome: 'Marie Curie', pais: 'Polônia/França', nascimento: '07/11/1867', morte: '04/07/1934', invencao: 'Radioatividade, polônio, rádio', texto: 'Marie Curie foi a primeira mulher a ganhar o Prêmio Nobel — e a única pessoa a ganhar em duas áreas diferentes: Física (1903) e Química (1911). Descobriu os elementos polônio e rádio e desenvolveu a teoria da radioatividade. Durante a Primeira Guerra Mundial, criou unidades móveis de raio-X que salvaram milhões de vidas. Morreu de anemia aplástica causada pela exposição à radiação de suas pesquisas.' },
  { nome: 'Isaac Newton', pais: 'Inglaterra', nascimento: '04/01/1643', morte: '31/03/1727', invencao: 'Lei da Gravitação Universal, cálculo, óptica', texto: 'Newton formulou a Lei da Gravitação Universal, as três Leis do Movimento e os Princípios Matemáticos da Filosofia Natural — a obra científica mais influente já escrita. Inventou o cálculo diferencial (simultaneamente com Leibniz). Descobriu que a luz branca é composta de todas as cores do espectro. Tudo isso durante uma quarentena de dois anos em que a Universidade de Cambridge fechou devido à Peste Bubônica.' },
  { nome: 'Albert Einstein', pais: 'Alemanha/EUA', nascimento: '14/03/1879', morte: '18/04/1955', invencao: 'Teoria da Relatividade, fóton, E=mc²', texto: 'Einstein publicou quatro artigos revolucionários em 1905 — seu "Annus Mirabilis" — que transformaram a física: o efeito fotoelétrico (que lhe rendeu o Nobel de 1921), o movimento Browniano, a relatividade especial e a equivalência massa-energia (E=mc²). A relatividade geral (1915) revolucionou nossa compreensão do espaço, tempo e gravidade. Sua fórmula E=mc² abriu o caminho para a energia nuclear.' },
  { nome: 'Alan Turing', pais: 'Inglaterra', nascimento: '23/06/1912', morte: '07/06/1954', invencao: 'Computação moderna, quebra do Enigma', texto: 'Considerado o pai da computação moderna, Turing concebeu a "Máquina de Turing" — modelo teórico de computador universal. Durante a Segunda Guerra Mundial, liderou a equipe que quebrou o código Enigma nazista, contribuindo decisivamente para o fim da guerra — historiadores estimam que encurtou a guerra em 2 anos e salvou 14 milhões de vidas. Perseguido pela homossexualidade, foi castrado quimicamente e morreu de envenenamento por cianeto.' },
  { nome: 'Santos-Dumont', pais: 'Brasil/França', nascimento: '20/07/1873', morte: '23/07/1932', invencao: '14-Bis (primeiro voo automotor documentado)', texto: 'Alberto Santos-Dumont foi o inventor brasileiro que demonstrou publicamente o primeiro voo automotor em Paris em 1906 com o 14-Bis — sem catapulta, sem vento e sem rampa. Os Irmãos Wright voaram em 1903, mas com vento e catapulta, sem testemunhas credenciadas. Santos-Dumont também inventou o relógio de pulso (para poder ler o tempo durante voos), o dirigível prático e o balão esférico. É considerado por muitos o pai da aviação.' },
  { nome: 'Oswaldo Cruz', pais: 'Brasil', nascimento: '05/08/1872', morte: '11/02/1917', invencao: 'Erradicação da febre amarela, varíola e peste no Brasil', texto: 'Oswaldo Cruz foi o médico sanitarista que erradicou a febre amarela do Rio de Janeiro em 1903-1904, tornando a cidade habitável após décadas de epidemias devastadoras. Sua vacinação obrigatória contra a varíola gerou a Revolta da Vacina, mas salvou incontáveis vidas. Fundou o Instituto Oswaldo Cruz (Fiocruz), que até hoje é referência mundial em pesquisa médica tropical. Morreu aos 44 anos por complicações renais.' },
]

const mulheres = [
  { nome: 'Cleópatra VII', periodo: 'Século I a.C.', pais: 'Egito', legado: 'Última faraó do Egito, aliou-se a César e Marco Antônio para preservar o Egito', texto: 'Cleópatra VII (69-30 a.C.) foi a última faraó do Egito antes da conquista romana. Descendente de macedônios, foi a primeira de sua dinastia a aprender a língua egípcia. Notável política e diplomata, aliou-se a Júlio César e depois a Marco Antônio para preservar a independência do Egito. Quando Otávio a derrotou, suicidou-se com a picada de uma serpente (segundo a lenda) para evitar ser exibida no triunfo romano. Falava 9 idiomas.' },
  { nome: 'Joana d\'Arc', periodo: 'Século XV', pais: 'França', legado: 'Liderou exércitos franceses na Guerra dos Cem Anos e mudou o curso da história europeia', texto: 'Joana d\'Arc (1412-1431) foi uma camponesa analfabeta de 17 anos que afirmou receber visões divinas ordenando-lhe libertar a França dos ingleses. Liderou o exército francês com tal bravura que quebrou o cerco de Orléans em 1429 e fez coroar o rei Carlos VII em Reims. Capturada pelos ingleses, foi queimada viva como herege aos 19 anos. Canonizada em 1920, é hoje um símbolo nacional francês e uma das mulheres mais famosas da história.' },
  { nome: 'Marie Curie', periodo: 'Séculos XIX-XX', pais: 'Polônia/França', legado: 'Única pessoa a ganhar Nobel em duas áreas científicas diferentes', texto: 'Marie Curie (1867-1934) foi a primeira mulher a ganhar o Prêmio Nobel e a única a ganhar em duas áreas: Física (1903) e Química (1911). Descobriu os elementos polônio (em homenagem à Polônia) e rádio. Sua pesquisa sobre radioatividade revolucionou a física e a medicina. Durante a Primeira Guerra Mundial, criou unidades móveis de raio-X chamadas "petites Curies" que salvaram milhares de soldados. Morreu de doença causada pela própria pesquisa.' },
  { nome: 'Rosa Parks', periodo: 'Século XX', pais: 'EUA', legado: 'Seu gesto de recusa deu início ao Movimento pelos Direitos Civis', texto: 'Rosa Parks (1913-2005) ficou conhecida como a "mãe do Movimento pelos Direitos Civis" quando, em 1º de dezembro de 1955, recusou-se a ceder seu assento num ônibus de Montgomery, Alabama, para um passageiro branco. Seu gesto desencadeou o Boicote aos Ônibus de Montgomery — 381 dias de protesto que destruiu a segregação nos transportes públicos. Parks não foi a primeira a recusar-se — foi a escolhida deliberadamente pelo NAACP pela sua imagem pública respeitável.' },
  { nome: 'Indira Gandhi', periodo: 'Século XX', pais: 'Índia', legado: 'Primeira mulher a governar uma democracia populosa', texto: 'Indira Gandhi (1917-1984) foi a primeira mulher a se tornar Primeira-Ministra da Índia, governando de 1966 a 1977 e de 1980 a 1984. Liderou a Índia na vitória contra o Paquistão na Guerra de 1971, que criou Bangladesh. Introduziu a Revolução Verde que tornou a Índia autossuficiente em alimentos. Controvérsia marcou seu governo: o Estado de Emergência (1975-77) e a Operação Estrela Azul contra separatistas sikh em 1984 levaram ao seu assassinato pelos próprios guardas-costas sikhs.' },
  { nome: 'Frida Kahlo', periodo: 'Século XX', pais: 'México', legado: 'Ícone do surrealismo e símbolo de identidade mexicana e feminismo', texto: 'Frida Kahlo (1907-1954) transformou sua dor em arte extraordinária. Sobrevivendo a poliomielite na infância e um acidente de ônibus devastador aos 18 anos — que a deixou com fraturas múltiplas e dor crônica pelo resto da vida —, criou cerca de 200 pinturas intensamente pessoais, muitas autorretratos explorando identidade, política e sofrimento. Casada com Diego Rivera, virou ícone do feminismo, do orgulho mexicano e LGBTQ+ décadas após sua morte.' },
  { nome: 'Rainha Nzinga', periodo: 'Século XVII', pais: 'Angola', legado: 'Resistiu à escravidão portuguesa e defendeu a soberania africana por décadas', texto: 'Nzinga (1583-1663) foi rainha do Ndongo e Matamba (atual Angola) que resistiu à expansão portuguesa e ao tráfico de escravos por décadas. Negociadora brilhante, converteu-se ao catolicismo e aprendeu português para negociar em igualdade com os colonizadores. Quando as negociações falharam, liderou guerrilhas e aliou-se com os holandeses contra Portugal. Governou até os 80 anos, tornando-se símbolo da resistência africana ao colonialismo.' },
  { nome: 'Hipácia de Alexandria', periodo: 'Séculos IV-V d.C.', pais: 'Egito', legado: 'Primeira matemática e astrônoma documentada da história', texto: 'Hipácia (c. 360-415 d.C.) foi a primeira mulher na história conhecida como matemática e filósofa. Diretora da escola Neoplatônica de Alexandria, ensinava astronomia, matemática e filosofia. Seus alunos vinham de toda parte do mundo mediterrâneo. Era pagã numa época em que o Cristianismo se tornava dominante. Um grupo de cristãos fanáticos, incitado pelo bispo Cirilo de Alexandria, a assassinou brutalmente em 415 d.C. — arranhando sua carne com conchas de ostras e queimando seus restos.' },
]

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const tipo = searchParams.get('tipo') || 'viloes'
  const limitRaw = parseInt(searchParams.get('limit') || '20', 10)
  const offsetRaw = parseInt(searchParams.get('offset') || '0', 10)
  const limit = isNaN(limitRaw) || limitRaw < 1 ? 20 : Math.min(limitRaw, 100)
  const offset = isNaN(offsetRaw) || offsetRaw < 0 ? 0 : offsetRaw

  const dataMap: Record<string, typeof viloes | typeof inventores | typeof mulheres> = {
    viloes,
    inventores,
    mulheres,
  }

  const data = dataMap[tipo] || viloes
  const slice = data.slice(offset, offset + limit)

  return NextResponse.json({ tipo, total: data.length, data: slice })
}
