import { NextRequest, NextResponse } from 'next/server'

const civilizacoes: Record<string, { titulo: string; texto: string; imagem: string }> = {
  '1-5': { titulo: 'Civilização Árabe - Origens e Expansão', texto: 'A história dos árabes está ligada à Península Arábica, onde inicialmente eram nômades, vivendo entre desertos e oásis. No final do século VI, Maomé teve uma revelação divina e se tornou o profeta de Alá. Sua pregação atraiu muitos seguidores e o islamismo se espalhou rapidamente, levando à conversão em massa dos árabes e à expansão islâmica entre os séculos VII e VIII, alcançando o norte da África, a Península Ibérica e partes do Oriente.', imagem: 'https://static.historiadomundo.com.br/conteudo/images/a-civilizacao-arabe-esteve-marcada-pelo-processo-expansao-religiao-islamica-53f660f960262.jpg' },
  '1-12': { titulo: 'A Língua Árabe', texto: 'A língua árabe, considerada sagrada pelos muçulmanos, é usada em diversos dialetos do Marrocos ao Iraque. Revelado através do Alcorão, o árabe se tornou a língua mais difundida entre as línguas semíticas. Cerca de 150 milhões de pessoas falam árabe como língua materna. A escrita árabe vai da direita para a esquerda. Durante a Idade Média, mais de 600 vocábulos árabes foram incorporados ao português: algodão, alfândega, álcool, alquimia, algarismo.', imagem: 'https://cdn-blog.superprof.com/blog_br/wp-content/uploads/2018/11/aprender-a-lingua-arabe.jpg.webp' },
  '2-2': { titulo: 'Grécia Antiga - Berço da Civilização Ocidental', texto: 'A Grécia Antiga é considerada o berço da civilização ocidental, florescendo entre os séculos VIII e II a.C. Organizada em cidades-estado (polis), a Grécia desenvolveu sistemas políticos, filosóficos e culturais únicos. Atenas criou a democracia direta sob Clístenes em 508 a.C. As Olimpíadas, fundadas em 776 a.C., reuniam atletas de toda a Hélade. Filósofos como Sócrates, Platão e Aristóteles estabeleceram os fundamentos do pensamento racional ocidental.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Parthenon_in_Athens.jpg/320px-The_Parthenon_in_Athens.jpg' },
  '2-9': { titulo: 'Democracia Ateniense', texto: 'A democracia ateniense, surgida no século VI a.C., é uma das maiores criações políticas da humanidade. O termo deriva do grego demos (povo) e kratos (poder). Clístenes reformou o sistema político ateniense por volta de 508 a.C. Sob Péricles (461-429 a.C.), a democracia atingiu seu auge: qualquer cidadão podia votar na Assembleia. Apenas cidadãos homens livres participavam — mas o princípio estabelecido era revolucionário e moldou as democracias modernas.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/The_Pnyx_in_Athens.jpg/320px-The_Pnyx_in_Athens.jpg' },
  '2-16': { titulo: 'Esparta - A Cidade-Estado Guerreira', texto: 'Esparta foi uma das mais poderosas cidades-estado da Grécia, famosa por sua disciplina militar e austeridade. O sistema agogê submetia meninos a treinamento rigoroso desde os sete anos. As mulheres espartanas tinham liberdade incomum: praticavam esportes e gerenciavam propriedades. A rivalidade com Atenas culminou na Guerra do Peloponeso (431-404 a.C.), que Esparta venceu mas que enfraqueceu toda a Grécia.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Leonidas_statue_-_Sparta%2C_Greece.jpg/240px-Leonidas_statue_-_Sparta%2C_Greece.jpg' },
  '2-23': { titulo: 'Filosofia Grega - Sócrates, Platão e Aristóteles', texto: 'A filosofia grega, nascida no século VI a.C., representa uma das maiores revoluções intelectuais da história. Sócrates questionou as verdades absolutas com o método dialético, sendo condenado à morte em 399 a.C. Platão criou a Teoria das Ideias e fundou a Academia. Aristóteles sistematizou a lógica, a biologia, a política e a ética. Esse legado chegou ao Ocidente moderno através dos árabes e do Renascimento.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Aristotle_Busto_Romano_Museo_Nazionale_Romano.jpg/240px-Aristotle_Busto_Romano_Museo_Nazionale_Romano.jpg' },
  '3-1': { titulo: 'Roma Antiga - Das Origens à República', texto: 'Roma surgiu como pequena cidade-estado às margens do rio Tibre. O último rei, Tarquínio, foi deposto em 509 a.C., dando início à República Romana. Dois cônsules eleitos anualmente governavam com o Senado. A República expandiu-se pela Itália, derrotou Cartago nas Guerras Púnicas e conquistou a Grécia. As guerras civis do século I a.C. levaram ao colapso da República e ao nascimento do Império.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Capitoline_she-wolf_Musei_Capitolini_MC1181.jpg/320px-Capitoline_she-wolf_Musei_Capitolini_MC1181.jpg' },
  '3-8': { titulo: 'O Império Romano - Augusto e a Pax Romana', texto: 'O Império Romano, estabelecido por Augusto em 27 a.C., abrangia da Grã-Bretanha à Mesopotâmia com mais de 70 milhões de habitantes. A Pax Romana — dois séculos de relativa paz — permitiu desenvolvimento cultural e econômico sem precedentes. A engenharia romana produziu estradas, aquedutos e coliseus que sobrevivem até hoje. O direito romano estabeleceu princípios jurídicos que fundamentam sistemas legais modernos em todo o mundo.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Augustus_of_Prima_Porta_%28inv._2290%29.jpg/240px-Augustus_of_Prima_Porta_%28inv._2290%29.jpg' },
  '3-29': { titulo: 'Bizâncio - O Segundo Império Romano', texto: 'O Império Bizantino sobreviveu por quase mil anos após a queda de Roma — de 395 a 1453 d.C. Sua capital Constantinopla era a maior e mais rica cidade da Europa medieval. Bizâncio preservou o conhecimento grego e romano e a lei romana foi codificada por Justiniano no Corpus Juris Civilis. A conquista de Constantinopla por Mehmed II em 1453 marcou o fim da Idade Média e forçou sábios gregos a fugirem para a Itália, alimentando o Renascimento.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Hagia_Sophia_Mars_2013.jpg/320px-Hagia_Sophia_Mars_2013.jpg' },
  '4-5': { titulo: 'China Antiga - Primeiras Dinastias', texto: 'A civilização chinesa tem mais de quatro mil anos de história documentada. As Dinastias Xia e Shang estabeleceram escrita pictográfica e ritual ancestral. Confúcio pregou harmonia social; Sun Tzu escreveu A Arte da Guerra. Qin Shi Huang, o primeiro imperador, unificou a Grande Muralha. A Dinastia Han inaugurou a Rota da Seda. Quatro grandes invenções chinesas mudaram o mundo: papel, imprensa, pólvora e bússola.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/320px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg' },
  '5-3': { titulo: 'Os Maias - Astronomia e Calendário', texto: 'Os Maias desenvolveram uma das civilizações mais sofisticadas das Américas, com cidades magnificentes como Tikal e Chichen Itzá. Calcularam o ano solar com precisão de segundos sem telescópio, previram eclipses com séculos de antecedência e desenvolveram o conceito de zero independentemente. O famoso Calendário Maia combina ciclos de 260 e 365 dias. A escrita maia hieroglífica foi finalmente decifrada no século XX.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/320px-Chichen_Itza_3.jpg' },
  '5-10': { titulo: 'Os Astecas - O Império do Sol', texto: 'O Império Asteca tinha capital em Tenochtitlan — atual Cidade do México — com 200 a 300 mil habitantes no auge, maior que a maioria das cidades europeias da época. Os jardins flutuantes (chinampas) tornavam a cidade autossuficiente. A religião exigia sacrifícios humanos para alimentar o sol. Hernán Cortés, com 500 homens, alianças com povos subjugados e a devastação da varíola, derrubou o Império em 1521.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Tenochtitlan.jpg/320px-Tenochtitlan.jpg' },
  '5-17': { titulo: 'Os Incas - O Maior Império das Américas', texto: 'O Tawantinsuyu (Império Inca) estendia-se por 4.000 km ao longo dos Andes com capital em Cusco. Governava de 10 a 15 milhões de pessoas e construiu 40.000 km de estradas. Machu Picchu é uma das maravilhas da engenharia humana. Sem roda, sem ferro e sem escrita convencional, organizaram um Estado sofisticado com distribuição de alimentos e medicina avançada. Francisco Pizarro destruiu o Império em 1532-1572.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/320px-Machu_Picchu%2C_Peru.jpg' },
  '7-5': { titulo: 'Os Vikings - Guerreiros e Exploradores', texto: 'Os Vikings foram povos escandinavos que entre os séculos VIII e XI saíram de seus fjords para explorar, comerciar e pilhar da América do Norte ao Mar Cáspio. Leif Erikson chegou à América do Norte em torno do ano 1000 d.C. — cinco séculos antes de Colombo. Os Vikings fundaram Dublin, Kiev e Novgorod; chegaram à Constantinopla como Guardas Varangianos do imperador. Tinham sofisticada poesia (Eddas) e sistema jurídico (Things).', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Gokstad_viking_ship_2.jpg/320px-Gokstad_viking_ship_2.jpg' },
  '8-2': { titulo: 'Mesopotâmia - Berço da Civilização', texto: 'A Mesopotâmia, entre os rios Tigre e Eufrates (atual Iraque), viu surgir as primeiras cidades, a escrita e o Estado organizado por volta de 4000 a.C. Os sumérios criaram a escrita cuneiforme, a roda, o arado e o calendário lunar. O Código de Hamurabi (c. 1750 a.C.) foi um dos primeiros conjuntos de leis escritas. A Epopeia de Gilgamesh é a obra literária mais antiga do mundo. A matemática em base 60 ainda é usada em horas e graus.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/P1150884_Louvre_Code_Hammurabi_face_rwk.jpg/240px-P1150884_Louvre_Code_Hammurabi_face_rwk.jpg' },
  '9-20': { titulo: 'Egito Antigo - Faraós e Pirâmides', texto: 'O Egito Antigo floresceu às margens do Nilo por mais de três mil anos (c. 3100 a.C. a 30 a.C.). O faraó era governante divino, filho de Ra. As pirâmides, construídas como tumbas reais, são os únicos monumentos das Sete Maravilhas do Mundo Antigo ainda em pé. A Grande Pirâmide de Gizé, de 2560 a.C., permanece uma das maiores estruturas já construídas. A escrita hieroglífica e o papiro registraram medicina, matemática e astronomia.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/320px-Kheops-Pyramid.jpg' },
  '10-4': { titulo: 'O Império Mali - Mansa Musa e o Ouro Africano', texto: 'O Império Mali foi o maior Estado da África Ocidental medieval, fundado por Sundiata Keita em 1235. As cidades de Timbuktu e Djenné eram centros de comércio e saber. Mansa Musa (1312-1337) é considerado o homem mais rico de toda a história, com riqueza estimada em US$ 400 bilhões em valores atuais. Sua peregrinação à Meca em 1324 com toneladas de ouro fez o preço do metal despencar por décadas no Oriente Médio.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Mansa_Musa.jpg/240px-Mansa_Musa.jpg' },
  '11-1': { titulo: 'Os Mongóis - O Maior Império Terrestre', texto: 'O Império Mongol, fundado por Gengis Khan em 1206, foi o maior império contíguo da história — 33 milhões de km². Suas campanhas mataram cerca de 40 milhões de pessoas — 10% da população mundial da época. O Pax Mongolica facilitou o comércio transcontinental e Marco Polo viajou sob proteção mongola. O Império fragmentou-se no século XIV, mas os mongóis transformaram permanentemente a Eurásia, da China à Europa Oriental.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/YuanEmperorAlbumGenghisPortrait.jpg/240px-YuanEmperorAlbumGenghisPortrait.jpg' },
  '11-8': { titulo: 'O Império Otomano', texto: 'O Império Otomano existiu de 1299 a 1923 — mais de 600 anos. A conquista de Constantinopla pelo sultão Mehmed II em 1453 encerrando o Império Bizantino foi o evento mais marcante do século XV. Solimão, o Magnífico, liderou o auge otomano: o Império estendia-se da Hungria ao Iêmen. A proclamação da República Turca por Atatürk em 1923 encerrou um dos mais longos impérios da história mundial.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Suleiman_the_Magnificent.jpg/240px-Suleiman_the_Magnificent.jpg' },
  '12-6': { titulo: 'O Renascimento Italiano', texto: 'O Renascimento floresceu na Itália entre os séculos XIV e XVI, representando uma redescoberta da cultura greco-romana. Leonardo da Vinci pintou a Mona Lisa e o Último Ceia, sendo também engenheiro, arquiteto e anatomista. Michelangelo criou o Davi e pintou o teto da Capela Sistina. Maquiavel escreveu O Príncipe. A imprensa de Gutenberg (1450) difundiu todas essas ideias, transformando para sempre a transmissão do conhecimento humano.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/240px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg' },
  '12-20': { titulo: 'As Grandes Navegações', texto: 'As Grandes Navegações dos séculos XV e XVI conectaram continentes antes separados. Bartolomeu Dias dobrou o Cabo da Boa Esperança em 1488; Vasco da Gama chegou à Índia em 1498; Colombo chegou às Américas em 1492; Cabral aportou no Brasil em 1500; Magalhães iniciou a primeira circunavegação do globo em 1519. As Navegações iniciaram a globalização, mas também o colonialismo, a escravidão africana e o genocídio indígena.', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Vasco_da_Gama_-_1524_portrait.jpg/240px-Vasco_da_Gama_-_1524_portrait.jpg' },
}

function getTodayCivilizacao() {
  const now = new Date()
  const month = now.getMonth() + 1
  const day = now.getDate()
  const key = `${month}-${day}`

  if (civilizacoes[key]) return { key, ...civilizacoes[key] }

  // Find closest weekly entry
  const keys = Object.keys(civilizacoes)
  const todayNum = month * 100 + day
  let closest = keys[0]
  let minDiff = Infinity

  for (const k of keys) {
    const [m, d] = k.split('-').map(Number)
    const diff = Math.abs(m * 100 + d - todayNum)
    if (diff < minDiff) {
      minDiff = diff
      closest = k
    }
  }
  return { key: closest, ...civilizacoes[closest] }
}

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const date = searchParams.get('date')
  const all = searchParams.get('all')

  if (all === 'true') {
    return NextResponse.json(civilizacoes)
  }

  if (date && civilizacoes[date]) {
    return NextResponse.json(civilizacoes[date])
  }

  return NextResponse.json(getTodayCivilizacao())
}
