import { NextResponse } from 'next/server'

const curiosidades = [
  { titulo: 'A Grande Biblioteca de Alexandria', texto: 'A Biblioteca de Alexandria, fundada no século III a.C. no Egito, foi o maior repositório de conhecimento do mundo antigo, com estimados 700.000 pergaminhos. Não foi destruída por um único incêndio — sua decadência foi gradual, ao longo de séculos. Júlio César acidentalmente queimou parte em 48 a.C.; o imperador romano Aurélio destruiu o bairro onde ficava em 270 d.C. O que a humanidade perdeu para sempre é incalculável.' },
  { titulo: 'O Código de Hamurabi', texto: 'O Código de Hamurabi, gravado numa estela de pedra negra de 2,25 metros por volta de 1750 a.C., contém 282 leis da Babilônia. É famoso pela lei do talião — "olho por olho, dente por dente" — mas também regulava salários, heranças e contratos. O médico que perdesse um paciente teria sua mão cortada. A pedra foi descoberta por arqueólogos franceses em 1901 e está no Louvre, em Paris.' },
  { titulo: 'A Batalha de Canas', texto: 'A Batalha de Canas (216 a.C.) é considerada a obra-prima da história militar. O general cartaginês Aníbal, com 40.000 homens, cercou e destruiu um exército romano de 80.000. Cerca de 70.000 romanos foram mortos em um único dia — mais que qualquer batalha da Segunda Guerra Mundial. A manobra de duplo envolvimento de Aníbal ainda é estudada nas academias militares do mundo todo.' },
  { titulo: 'As Cruzadas Infantis', texto: 'Em 1212, dois jovens — Estevão de Cloyes, na França, e Nicolau de Colônia, na Alemanha — lideraram movimentos conhecidos como Cruzadas Infantis. Milhares de crianças marcharam em direção à Terra Santa acreditando que Deus abriria o mar para elas. Muitas morreram de fome e doença no caminho. As que chegaram ao Mediterrâneo encontraram o mar fechado; muitas foram vendidas como escravas no norte da África.' },
  { titulo: 'A Morte de Gengis Khan', texto: 'A causa exata da morte de Gengis Khan em 1227 permanece um mistério histórico. As teorias incluem: queda do cavalo, ferida de batalha, tifoide, ou mesmo uma flechada por uma princesa Tangut que ele havia capturado. Seu túmulo foi deliberadamente escondido — soldados que acompanharam o cortejo fúnebre foram executados para guardar o segredo. Arqueólogos ainda buscam o local exato no coração da Mongólia.' },
  { titulo: 'A Biblioteca de Ivan, o Terrível', texto: 'Ivan, o Terrível, czar da Rússia, possuía uma lendária biblioteca de manuscritos gregos, latinos e hebreus — trazidos para a Rússia após a queda de Constantinopla em 1453. Chamada de "Biblioteca de Ivan" ou "Biblioteca Dourada de Moscou", ela desapareceu após sua morte em 1584. Alguns acreditam que está escondida em câmaras subterrâneas sob o Kremlin. Nenhum arqueólogo jamais a encontrou.' },
  { titulo: 'O Saque de Roma em 410 d.C.', texto: 'Quando os visigodos de Alarico saquearam Roma em 410 d.C., foi o primeiro saque da "Cidade Eterna" em 800 anos. O choque foi tão grande que Santo Agostinho escreveu "A Cidade de Deus" para explicar como Deus poderia permitir tal coisa. Mas o saque foi surpreendentemente civilizado: os visigodos eram cristãos e respeitaram as igrejas. Três dias depois, partiram com butim — mas não destruíram a cidade.' },
  { titulo: 'A Morte de Alexandre, o Grande', texto: 'Alexandre, o Grande, morreu em Babilônia em 323 a.C. aos 32 anos. As causas ainda são debatidas: intoxicação por tifóide e malária (teoria mais aceita), envenenamento (muitos tinham motivos), ou consumo excessivo de vinho. O que é certo: após sua morte, seu vasto Império, que ia da Grécia à Índia, foi dividido entre seus generais e implodiu em guerras. Alexandre nunca perdeu uma batalha em 13 anos de conquistas.' },
  { titulo: 'Os Assassinos Medievais', texto: 'A lenda dos Assassinos — a seita ismailita Nizari liderada pelo "Velho da Montanha" no século XI-XIII — deu origem à palavra "assassino". Baseados no castelo de Alamut, no atual Irã, eram mestres da infiltração e do assassinato político. Marco Polo descreveu como o líder drogava recrutas com haxixe (hashish → Hashshashin → assassino) para fazê-los acreditar que haviam visitado o paraíso — motivando-os ao sacrifício.' },
  { titulo: 'A Construção das Pirâmides', texto: 'As pirâmides de Gizé não foram construídas por escravos — os trabalhadores eram trabalhadores contratados que recebiam pagamento em cerveja, pão e medicina. Arqueólogos descobriram um cemitério dos construtores e diários de trabalho. A Grande Pirâmide de Quéops (2560 a.C.) usou 2,3 milhões de blocos com peso médio de 2,5 toneladas cada. Os egípcios transportavam os blocos com trenós e água como lubrificante.' },
  { titulo: 'A Rota da Seda e a Peste Negra', texto: 'A Peste Negra, que matou um terço da população europeia (1347-1353), chegou à Europa pela Rota da Seda. Mercadores da Crimeia trouxeram-na de volta da Ásia Central. A cidade de Caffa (atual Feodósia), sitiada pelos mongóis, viu os atacantes catapultar cadáveres de vítimas da peste para dentro dos muros — um dos primeiros exemplos documentados de guerra biológica. Os mercadores genoveses que fugiram espalharam a doença pelo Mediterrâneo.' },
  { titulo: 'O Enigma dos Moai', texto: 'As estátuas Moai da Ilha de Páscoa, esculpidas entre os séculos XIII e XVI, pesam em média 14 toneladas — algumas chegam a 82. Os habitantes da ilha as transportaram sem roda nem animais de carga. A teoria mais aceita hoje: as estátuas foram "caminhadas" erguidas e balançadas por equipes com cordas. A civilização Rapanui que as criou entrou em colapso — possivelmente pela desflorestação causada pelo esforço de transporte.' },
  { titulo: 'O Exército de Terracota', texto: 'O Exército de Terracota do imperador Qin Shi Huang, descoberto em 1974 por agricultores na China, contém mais de 8.000 soldados, 130 carruagens e 520 cavalos esculpidos em tamanho real — cada rosto é único e distinto. Construído para proteger o imperador na vida após a morte, o complexo funerário inteiro (ainda não totalmente escavado) pode ser maior que algumas cidades modernas. Uma tumba central ainda está intacta.' },
  { titulo: 'Cleópatra Viveu Mais Perto de Nós que das Pirâmides', texto: 'Cleópatra VII (69-30 a.C.) é frequentemente associada às pirâmides egípcias. Mas as pirâmides foram construídas por volta de 2560 a.C. — 2.490 anos antes de Cleópatra nascer. Ela viveu mais próxima no tempo do iPhone (2007) do que das pirâmides. Além disso, Cleópatra era de origem macedônia-grega (dinastia Ptolomaica) e foi a primeira de sua dinastia a aprender o egípcio — as línguas de seus ancestrais eram o grego e o macedônio.' },
  { titulo: 'A Batalha de Lepanto', texto: 'A Batalha de Lepanto (7 de outubro de 1571) foi o maior combate naval desde a Antiguidade. Uma frota da Liga Santa (Espanha, Veneza, Papado) enfrentou a frota Otomana no Golfo de Lepanto, Grécia. Resultado: 40.000 mortos e 300 navios destruídos em um único dia. Os cristãos venceram, encerrando o mito de invencibilidade naval otomana. Miguel de Cervantes, autor do Dom Quixote, lutou na batalha e perdeu o uso da mão esquerda.' },
  { titulo: 'O Segredo dos Gregos Antigos', texto: 'O "fogo grego" foi uma arma incendiária usada pelo Império Bizantino a partir do século VII que queimava mesmo na água — impossível de apagar. Destruiu frotas árabes que tentavam conquistar Constantinopla em 678 e 717 d.C. A fórmula exata foi um segredo de Estado tão bem guardado que foi perdida para sempre quando Bizâncio caiu em 1453. Historiadores modernos acreditam que continha nafta, cal e possivelmente enxofre.' },
  { titulo: 'O Tratado de Tordesilhas', texto: 'O Tratado de Tordesilhas (1494) dividiu o mundo entre Portugal e Espanha através de uma linha imaginária no Atlântico — 370 léguas a oeste de Cabo Verde. Tudo a oeste seria espanhol; a leste, português. O Brasil ficou (por pouco) do lado português. O problema: as outras potências europeias (França, Inglaterra, Holanda) ignoraram completamente o tratado, levando a séculos de guerras coloniais. O papa Alexandre VI mediou o acordo.' },
  { titulo: 'A Descoberta da América por Colombo', texto: 'Cristóvão Colombo morreu em 1506 acreditando ter chegado à Ásia — ele nunca aceitou ter descoberto um continente novo. Américo Vespúcio foi quem concluiu em 1503 que aquelas terras eram um "Novo Mundo" (Mundus Novus), e por isso o continente recebeu seu nome. Colombo, em suas quatro viagens, nunca pisou no território que hoje é os Estados Unidos — visitou as Antilhas, Venezuela, América Central e Honduras.' },
  { titulo: 'A Traição de Judas', texto: 'Segundo os Evangelhos, Judas Iscariotes traiu Jesus por 30 moedas de prata — o preço de um escravo na lei mosaica. A identidade das "30 moedas" é debatida: poderiam ser siclos de Tiro, que eram a moeda aceita no Templo de Jerusalém. Judas devolveu o dinheiro aos sacerdotes e se suicidou. Os sacerdotes usaram as moedas para comprar um campo chamado "Campo do Sangue". Uma moeda de prata tiria foi descoberta em escavações no Monte do Templo em Jerusalém.' },
  { titulo: 'O Mistério dos Templários', texto: 'A Ordem dos Templários, fundada em 1119 para proteger peregrinos na Terra Santa, tornou-se a organização bancária mais poderosa da Europa medieval — inventaram as letras de câmbio, precursoras dos cheques. Em 1307, o rei Felipe IV da França, endividado com os Templários, fez prender todos os membros, acusando-os de heresia, sodomia e adoração do demônio Baphomet. O papa Clemente V dissolveu a ordem em 1312. O suposto tesouro dos Templários nunca foi encontrado.' },
  { titulo: 'A Gripe Espanhola de 1918', texto: 'A gripe espanhola de 1918-1920 foi a pandemia mais mortal da história moderna: matou entre 50 e 100 milhões de pessoas — mais que toda a Primeira Guerra Mundial. Chamada de "espanhola" não porque surgiu na Espanha, mas porque a Espanha (país neutro na guerra) foi o único que não censurou notícias sobre ela. Países beligerantes suprimiram informações para não desanimar suas tropas. A pandemia infectou 500 milhões de pessoas, um terço da população mundial da época.' },
  { titulo: 'A Batalha de Stalingrado', texto: 'A Batalha de Stalingrado (agosto 1942 - fevereiro 1943) foi o ponto de virada da Segunda Guerra Mundial. Mais de 2 milhões de pessoas morreram na batalha mais sangrenta da história — combates rua por rua, prédio por prédio. O General Paulus, do Exército alemão, rendeu-se com 91.000 soldados — a primeira rendição de um general alemão na guerra. A derrota em Stalingrado marcou o início do recuo alemão no front oriental.' },
  { titulo: 'O Dia D - Operação Overlord', texto: 'O Desembarque na Normandia (6 de junho de 1944) foi a maior operação anfíbia da história: 156.000 soldados aliados cruzaram o Canal da Mancha em 5.000 navios e 11.000 aeronaves. Os alemães esperavam o ataque em Pas-de-Calais — uma enorme operação de engano (Operação Bodyguard) usou um exército fictício, dublês de Patton e sinais de rádio falsos para desorientar Hitler. O desembarque abriu a frente ocidental que libertou a Europa.' },
  { titulo: 'O Fim de Hitler', texto: 'Adolf Hitler suicidou-se no bunker da Chancelaria em Berlim em 30 de abril de 1945, enquanto as tropas soviéticas estavam a menos de 500 metros. Ingeriu cianeto e disparou na cabeça simultaneamente. Seu corpo e o de Eva Braun foram incinerados no jardim do bunker por ordens suas, para evitar que fossem exibidos como os corpos de Mussolini. Os soviéticos encontraram fragmentos do crânio e afirmam tê-los preservado — mas análises modernas levantam dúvidas.' },
  { titulo: 'A Bomba Atômica de Hiroshima', texto: 'A bomba atômica Little Boy, lançada sobre Hiroshima em 6 de agosto de 1945, explodiu a 600 metros de altitude com força de 16.000 toneladas de TNT. Em segundos, 70.000 a 80.000 pessoas morreram. Até o fim de 1945, o total chegava a 140.000. O piloto, o coronel Paul Tibbets, não manifestou remorso: disse ter dormido bem nas noites seguintes. Três dias depois, Nagasaki foi atingida. O Japão rendeu-se em 15 de agosto de 1945.' },
  { titulo: 'A Revolução Francesa e a Guilhotina', texto: 'A guilhotina foi proposta pelo médico Joseph-Ignace Guillotin em 1789 como forma humanitária de execução — igual para todas as classes, sem sofrimento prolongado. Durante o Terror (1793-1794), cerca de 17.000 pessoas foram guilhotinadas, incluindo o próprio rei Luís XVI e a rainha Maria Antonieta. Ironicamente, Guillotin nunca quis associar seu nome ao instrumento e passou o resto da vida tentando mudar o nome da máquina. Falhou.' },
  { titulo: 'Napoleão e o Código Civil', texto: 'O maior legado de Napoleão Bonaparte não são suas batalhas, mas o Código Civil de 1804 — o Código Napoleônico. Adotado por dezenas de países, incluindo o Brasil, codificou princípios da igualdade perante a lei, propriedade privada, liberdade de contratos e laicidade do Estado. O Código influenciou os sistemas jurídicos de mais de 40 países. Napoleão disse que sua única batalha verdadeiramente imortal foi o Código Civil — não Austerlitz ou Jena.' },
  { titulo: 'A Independência do Brasil', texto: 'A independência do Brasil em 7 de setembro de 1822 foi um processo surpreendentemente pacífico comparado às revoluções americana e francesa. Dom Pedro I, filho do rei português João VI, ficou no Brasil ao invés de retornar a Portugal. Pressionado pelas Cortes Portuguesas a tornar o Brasil uma colônia novamente, proclamou a independência às margens do rio Ipiranga. A monarquia brasileira (1822-1889) foi a única na América do Sul — e durou 67 anos.' },
  { titulo: 'O Triângulo das Bermudas', texto: 'O Triângulo das Bermudas, área entre Flórida, Bermudas e Porto Rico, ganhou fama de "maldito" por supostos desaparecimentos de navios e aviões. A realidade: estudos modernos (incluindo uma análise de 2016 da Seguradora Lloyd\'s de Londres) mostram que a área não tem taxas de acidentes acima da média mundial. Muitos dos "desaparecimentos" relatados nunca ocorreram, foram exagerados ou aconteceram fora do triângulo. O mito nasceu de um artigo de 1950 e explodiu nos anos 1970.' },
  { titulo: 'A Queda do Muro de Berlim', texto: 'O Muro de Berlim caiu em 9 de novembro de 1989 por causa de um erro burocrático. O porta-voz do Partido Comunista da Alemanha Oriental, Günter Schabowski, recebeu uma nota informando que novos regulamentos de viagem entrariam em vigor — mas não sabia quando. Numa coletiva de imprensa ao vivo, quando perguntado, consultou suas notas e disse "imediatamente, sem demora". A notícia se espalhou e alemães orientais foram para os postos de controle — que os guardas, sem ordens claras, acabaram abrindo.' },
  { titulo: 'O Custo da Primeira Guerra Mundial', texto: 'A Primeira Guerra Mundial (1914-1918) matou cerca de 20 milhões de pessoas, militares e civis. Mas o custo humano real foi muito maior: a gripe espanhola, que matou 50-100 milhões, foi facilitada pelas condições criadas pela guerra. Além disso, a Primeira Guerra destruiu quatro impérios — o Austro-Húngaro, o Russo, o Otomano e o Alemão — e criou as condições para a Segunda Guerra Mundial. Churchill disse que a Segunda foi "a consequência inevitável" da Primeira.' },
]

export async function GET() {
  const now = new Date()
  const day = now.getDate()
  const index = (day - 1) % curiosidades.length
  return NextResponse.json(curiosidades[index])
}
